networks:
  schreck-net:
    driver: bridge

services:
  schreck-mongo:
    image: mongo:latest
    container_name: schreck-mongo
    networks:
      - schreck-net
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=schreck
      - MONGO_INITDB_ROOT_PASSWORD=Q1w2e3r4
    volumes:
      - schreck-mongo-data:/data/db
      
  schreck-server:
    build:
      context: .
      dockerfile: Dockerfile.dev # DEV
    image: zoranbow/schreck-express:1
    container_name: schreck-server
    networks:
      - schreck-net
    ports:
      - "3000:3000"
    env_file:
      - .env 
    depends_on:
      - schreck-mongo
    volumes: # DEV
      - .:/home/app
    command: sh -c "npm i && nodemon index.js"

volumes:
  schreck-mongo-data:
